name: CI

on:
  push:
    branches: ['dev']
  pull_request:
    branches: ['dev']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Start containers
        run: docker-compose -f "docker-compose.yml" up -d --build

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: install modules
        run: yarn
      
      - name: Install dependencies
        run: npx lerna bootstrap

      - name: lint code
        run: lerna run lint

      - name: build project
        run: lerna run build

      - name: test
        run: lerna run test

      - name: Stop containers
        run: docker-compose -f "docker-compose.yml" down
