name: CI

on:
  push:
    branches: ['dev']
  pull_request:
    branches: ['dev']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Start containers
        run: docker-compose -f "docker-compose.yml" up -d --build

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: unshalow
        run: git fetch --prune --unshallow

      - name: install modules
        run: yarn

      - name: lint code
        run: yarn lint

      - name: format code
        run: yarn format

      - name: build project
        run: yarn build

      - name: test
        run: yarn test

      - name: Stop containers
        run: docker-compose -f "docker-compose.yml" down

      - name: add all files
        run: git add .

      - name: extract git commit data
        uses: rlespinasse/git-commit-data-action@v1.x

      - name: Update author information
        run: echo ${{env.GIT_COMMIT_AUTHOR_NAME}} > AUTHOR

      - name: make PR to main branch
        uses: peter-evans/create-pull-request@v3
        with:
          branch: auto-merge-dev-to-main
          base: main
          commiter: ${{env.GIT_COMMIT_AUTHOR_NAME}} <${{env.GIT_COMMIT_AUTHOR_EMAIL}}>
          author: ${{env.GIT_COMMIT_AUTHOR_NAME}} <${{env.GIT_COMMIT_AUTHOR_EMAIL}}>
          body: |
            This PR was automatically created by the GitHub Action, **CI**. 

            Contact the author of the action if you don't want to receive PRs like this.
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-branch: true
          labels: |
            automated pr
